# _*_ coding:utf-8 _*_
import re
from pyquery import PyQuery as pq
import sys
reload(sys)
sys.setdefaultencoding("utf-8")
s = """<div class="PCD_counter">
                            <div class="WB_innerwrap">
                                                            <table class="tb_counter" cellpadding="0" cellspacing="0">
                                                                                                <tbody>
                                                                                                                                        <tr>
                                                                                                                                                                                                                            <td class="S_line1">
                                                                                                                                                                                                                                                                                                                    <a bpfilter="page_frame" class="t_link S_txt1" href="http://weibo.com/p/1005055589322664/follow?from=page_100505&amp;wvr=6&amp;mod=headfollow#place"><strong class="W_f18">41</strong><span class="S_txt2">关注</span></a></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <td class="S_line1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a bpfilter="page_frame" class="t_link S_txt1" href="http://weibo.com/p/1005055589322664/follow?relate=fans&amp;from=100505&amp;wvr=6&amp;mod=headfans&amp;current=fans#place"><strong class="W_f18">13</strong><span class="S_txt2">粉丝</span></a></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <td class="S_line1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a bpfilter="page_frame" class="t_link S_txt1" href="http://weibo.com/p/1005055589322664/home?from=page_100505_profile&amp;wvr=6&amp;mod=data#place"><strong class="W_f18">17</strong><span class="S_txt2">微博</span></a></td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>"""
total_pq = pq(unicode(s))
data = total_pq("div.PCD_counter")

if not data:
    print "null"
else:
    counter_list = data.find('td')
#    for td in counter_list:
#        td = pq(td)
#        print td('strong').text()
    print counter_list.eq(1)('strong').text()
    print "not null"
#p = total_pq("p.comment_txt").text()
#print p
