# _*_ coding:utf-8 _*_
import re
from pyquery import PyQuery as pq
import sys
reload(sys)
sys.setdefaultencoding("utf-8")

s="""<ul class="WB_row_line WB_row_r4 clearfix S_line2">
                                    <li>
                                                                                        <a href="javascript:void(0);" class="S_txt2" action-type="fl_pop" action-data="mid=3948332907414244&amp;from=p_profile_pc_05" suda-uatrack="key=profile_feed&amp;value=popularize_host"><span class="pos"><span class="line S_line1">
                                                                                                                                                                            <i class="S_txt2" title="此条微博已经被阅读498次">阅读 498</i>&nbsp;
                                                                                                                                                                                                                                                                                                        推广                                                                            </span></span>
                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a action-data="allowForward=0&amp;url=http://weibo.com/5589322664/Dkhmiv6MA&amp;mid=3948332907414244&amp;name=航大东北王&amp;uid=5589322664&amp;domain=5589322664" action-type="fl_forward" action-history="rec=1" href="javascript:void(0);" class="S_txt2" suda-uatrack="key=profile_feed&amp;value=transfer"><span class="pos"><span class="line S_line1" node-type="forward_btn_text"><span><em class="W_ficon ficon_forward S_ficon"></em><em>1</em></span></span></span></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span class="arrow"><span class="W_arrow_bor W_arrow_bor_t"><i class="S_line1"></i><em class="S_bg1_br"></em></span></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="javascript:void(0);" class="S_txt2" action-type="fl_comment" action-data="ouid=5589322664&amp;location=profile&amp;comment_type=0" suda-uatrack="key=profile_feed&amp;value=comment:3948332907414244"><span class="pos"><span class="line S_line1" node-type="comment_btn_text"><span><em class="W_ficon ficon_repeat S_ficon"></em><em>评论</em></span></span></span></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span class="arrow"><span class="W_arrow_bor W_arrow_bor_t"><i class="S_line1"></i><em class="S_bg1_br"></em></span></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="javascript:void(0);" class="S_txt2" action-type="fl_like" action-data="version=mini&amp;qid=heart&amp;mid=3948332907414244&amp;loc=profile" title="赞" suda-uatrack="key=profile_feed&amp;value=like"><span class="pos"><span class="line S_line1"><span node-type="like_status"><i class="W_icon icon_praised_b"></i> <em>1</em></span></span></span></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span class="arrow"><span class="W_arrow_bor W_arrow_bor_t"><i class="S_line1"></i><em class="S_bg1_br"></em></span></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </ul>"""


s1="""<ul class="WB_row_line WB_row_r3 clearfix S_line2">
                                    <li>
                                                                                        <a href="javascript:void(0);" class="S_txt2" suda-uatrack="key=profile_feed&amp;value=popularize_host"><span class="pos"><span class="line S_line1">
                                                                                                                                                                            <i class="S_txt2" title="此条微博已经被阅读105次">阅读 105</i>&nbsp;
                                                                                                                                                                                                                                                            <i class="S_txt2" title="此条微博无法使用推广功能">推广</i>
                                                                                                                                                                                                                                                                                                </span></span>
                                                                                                                                                                                                                                                                                                                            </a>
                                                                                                                                                                                                                                                                                                                                                                        </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                        <li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="javascript:void(0);" class="S_txt2" action-type="fl_comment" action-data="ouid=5589322664&amp;location=profile&amp;comment_type=0" suda-uatrack="key=profile_feed&amp;value=comment:3948334014697596"><span class="pos"><span class="line S_line1" node-type="comment_btn_text"><span><em class="W_ficon ficon_repeat S_ficon"></em><em>评论</em></span></span></span></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span class="arrow"><span class="W_arrow_bor W_arrow_bor_t"><i class="S_line1"></i><em class="S_bg1_br"></em></span></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="javascript:void(0);" class="S_txt2" action-type="fl_like" action-data="version=mini&amp;qid=heart&amp;mid=3948334014697596&amp;loc=profile" title="赞" suda-uatrack="key=profile_feed&amp;value=like"><span class="pos"><span class="line S_line1"><span node-type="like_status"><i class="W_icon icon_praised_b"></i><em>赞</em></span></span></span></a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span class="arrow"><span class="W_arrow_bor W_arrow_bor_t"><i class="S_line1"></i><em class="S_bg1_br"></em></span></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </ul>"""


total_pq = pq(unicode(s1))
data = total_pq("ul.WB_row_line")

if not data:
    print "null"
else:
    print len(data.find('li'))
    print "not null"
